//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfRepresentation.Test.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfRepresantation.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Tables&quot;: [
        ///    {
        ///      &quot;Rows&quot;: [
        ///        {
        ///          &quot;Cells&quot;: [
        ///            {
        ///              &quot;Left&quot;: &quot;70.92&quot;,
        ///              &quot;Right&quot;: &quot;440.0661&quot;,
        ///              &quot;Bottom&quot;: &quot;279.5&quot;,
        ///              &quot;Top&quot;: &quot;269.8968&quot;,
        ///              &quot;Width&quot;: &quot;84.33392&quot;,
        ///              &quot;Height&quot;: &quot;289.1032&quot;,
        ///              &quot;Text&quot;: &quot;- EC type-approval&quot;
        ///            },
        ///            {
        ///              &quot;Left&quot;: &quot;294.34&quot;,
        ///              &quot;Right&quot;: &quot;219.7533&quot;,
        ///              &quot;Bottom&quot;: &quot;279.5&quot;,
        ///              &quot;Top&quot;: &quot;269.8968&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_json {
            get {
                return ResourceManager.GetString("001.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Tables xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Id=&quot;029-00001&quot;&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;58.344&quot; Bottom=&quot;178.5&quot; Top=&quot;173.35999&quot; Width=&quot;23.71428&quot;&gt;SUBJECT&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;59.184&quot; Bottom=&quot;194&quot; Top=&quot;183.83002&quot; Width=&quot;163.57175&quot;&gt;Whole Vehicle Type Approval&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;58.344&quot; Bottom=&quot;240.5&quot; Top=&quot;235.52002&quot; Width=&quot;22.996086&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_xml {
            get {
                return ResourceManager.GetString("002.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Tables xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Id=&quot;001-00001&quot;&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;70.92&quot; Bottom=&quot;45.5&quot; Top=&quot;35.816772&quot; Width=&quot;25.985008&quot;&gt;Eddy&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;326.08&quot; Bottom=&quot;45.5&quot; Top=&quot;38.91748&quot; Width=&quot;129.815&quot;&gt;Division Vehicle Regulation &amp;amp; Admission&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;242.8&quot; Bottom=&quot;118&quot; Top=&quot;108.236755&quot; Width=&quot;112 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_xml {
            get {
                return ResourceManager.GetString("003.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Tables xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Id=&quot;030-00002&quot;&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;71.784&quot; Bottom=&quot;88.5&quot; Top=&quot;83.45001&quot; Width=&quot;12.790802&quot;&gt;Item&lt;/Cell&gt;
        ///      &lt;Cell Left=&quot;209.69&quot; Bottom=&quot;88.5&quot; Top=&quot;83.45001&quot; Width=&quot;36.87445&quot;&gt;Drawing Title&lt;/Cell&gt;
        ///      &lt;Cell Left=&quot;358.15&quot; Bottom=&quot;88.5&quot; Top=&quot;83.45001&quot; Width=&quot;34.466705&quot;&gt;Drawing No.&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;73.944&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_xml {
            get {
                return ResourceManager.GetString("004.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Tables xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;Table Id=&quot;030-00001&quot;&gt;
        ///		&lt;Rows&gt;
        ///			&lt;Cell Left=&quot;58.344&quot; Bottom=&quot;70.5&quot; Top=&quot;65.33002&quot; Width=&quot;41.970238&quot;&gt;Annex III part I&lt;/Cell&gt;
        ///		&lt;/Rows&gt;
        ///		&lt;Rows&gt;
        ///			&lt;Cell Left=&quot;58.344&quot; Bottom=&quot;79.5&quot; Top=&quot;74.33002&quot; Width=&quot;36.765007&quot;&gt;Attachments&lt;/Cell&gt;
        ///		&lt;/Rows&gt;
        ///	&lt;/Table&gt;
        ///	&lt;Table Id=&quot;030-00002&quot;&gt;
        ///		&lt;Rows&gt;
        ///			&lt;Cell Left=&quot;71.784&quot; Bottom=&quot;88.5&quot; Top=&quot;83.45001&quot; Width=&quot;12.79 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_xml {
            get {
                return ResourceManager.GetString("005.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Tables xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Table Id=&quot;001-00001&quot;&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;70.92&quot; Bottom=&quot;45.5&quot; Top=&quot;35.816772&quot; Width=&quot;25.985008&quot;&gt;Eddy&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;326.08&quot; Bottom=&quot;45.5&quot; Top=&quot;38.91748&quot; Width=&quot;129.815&quot;&gt;Division Vehicle Regulation &amp;amp; Admission&lt;/Cell&gt;
        ///    &lt;/Rows&gt;
        ///    &lt;Rows&gt;
        ///      &lt;Cell Left=&quot;242.8&quot; Bottom=&quot;118&quot; Top=&quot;108.236755&quot; Width=&quot;112 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normal_xml {
            get {
                return ResourceManager.GetString("Normal.xml", resourceCulture);
            }
        }
    }
}
